spring.datasource.url=jdbc:h2:mem:store_db
spring.h2.console.enabled=false
spring.datasource.username=sa
spring.datasource.password=

spring.security.user.name=user
spring.security.user.password=1234#

spring.security.admin.name=admin
spring.security.admin.password=##123

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always